M48
; DRILL file {KiCad (6.0.0)} date Thu Jan 12 10:54:35 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-12T10:54:35-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X152.515Y-42.53
X157.365Y-42.53
T2
X152.215Y-39.5
X157.665Y-39.5
T3
X95.123Y-54.864
X95.123Y-97.282
X155.194Y-54.864
X155.194Y-97.282
T0
M30
